"""PDF export helpers for bibliometrics reports."""

from __future__ import annotations

import base64
import logging
import unicodedata
from datetime import datetime
from io import BytesIO
from typing import Iterable, Mapping, Optional

from django.conf import settings
from django.http import HttpRequest
from django.utils.translation import override
from reportlab.lib import colors
from reportlab.lib.colors import blue
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from bibliodata.models import Author, Publication


def build_pdf_report(
    *,
    request: HttpRequest,
    pubs_queryset: Iterable[Publication],
    filters: Mapping[str, object],
    images: Mapping[str, Optional[str]],
    network_html: Optional[str],
    lang: str = "es",
    logger: Optional[logging.Logger] = None,
) -> bytes:
    """Build the bibliometrics PDF report and return the generated bytes.

    Args:
        request: Current HTTP request (used to build absolute links).
        pubs_queryset: Publications to include in the report.
        filters: Applied filters (years, areas, institutions, etc.).
        images: Base64-encoded PNG images for charts.
        network_html: Optional network HTML filename for keywords view.
        lang: Language code (e.g. 'es' or 'en') for i18n strings.
        logger: Optional logger.

    Returns:
        The generated PDF as bytes.
    """

    # NOTE:
    # We intentionally do *not* rely on django.po for report translations.
    # The report uses an internal ES/EN dictionary so the PDF is always
    # fully consistent (no mixed-language output).
    #
    # We still activate the requested language so any other Django-driven
    # translations (if present elsewhere) follow the same selection.
    with override(lang):
        return _build_pdf_report_impl(
            request=request,
            pubs_queryset=pubs_queryset,
            filters=filters,
            images=images,
            network_html=network_html,
            lang=lang,
            logger=logger,
        )


def _build_pdf_report_impl(
    *,
    request: HttpRequest,
    pubs_queryset: Iterable[Publication],
    filters: Mapping[str, object],
    images: Mapping[str, Optional[str]],
    network_html: Optional[str],
    lang: str,
    logger: Optional[logging.Logger] = None,
) -> bytes:
    """Internal implementation for building the PDF report.

    This function assumes the correct translation language is already active
    (see `build_pdf_report`).
    """

    logger = logger or logging.getLogger("django")

    lang = (lang or "es").split("-")[0].lower()
    if lang not in {"es", "en"}:
        lang = "es"

    # Internal translations for the PDF report (no django.po needed).
    # Keep keys stable; values are the user-facing strings.
    TXT = {
        "es": {
            "meta_title": "Bibliometría IPBLN: Informe",
            "report_title_author": "Informe bibliométrico de {author}",
            "report_title_filters": "Bibliometría IPBLN: Informe generado con filtros personalizados",
            "generated_on": "Fecha de generación",
            "all_areas": "Todas las áreas",
            "all_institutions": "Todas las instituciones",
            "all_types": "Todos los tipos",
            "all_quartiles": "Todos los cuartiles",
            "all_citations": "Todas (0 - máx)",
            "max": "máx",
            "year_from": "Año desde",
            "year_to": "Año hasta",
            "thematic_areas": "Áreas temáticas",
            "institutions": "Instituciones",
            "publication_types": "Tipos de publicación",
            "quartiles": "Cuartiles",
            "citations_range": "Citas (mín - máx)",
            "selected_author": "Autor seleccionado",
            "timeline": "Línea temporal de publicaciones",
            "areas_bar": "Distribución de áreas (gráfico de barras)",
            "areas_pie": "Distribución de áreas (gráfico circular)",
            "charts_missing": "No se han podido exportar los gráficos.",
            "view_networks": "Ver redes de colaboración",
            "departments": "Departamentos",
            "louvain": "Louvain",
            "leiden": "Leiden",
            "communities": "comunidades",
            "keywords_network": "Red de coautorías por palabras clave",
            "selected_author_metrics": "Métricas del autor seleccionado",
            "orcid": "ORCID",
            "total_publications": "Total publicaciones",
            "total_citations": "Total citas",
            "citations_wos": "Citas WoS",
            "citations_scopus": "Citas Scopus",
            "h_index": "Índice h (WoS/Scopus)",
            "h_index_gb": "Índice h GESBIB",
            "h_index_h5gb": "Índice h5 GESBIB",
            "international_index": "Índice internacionalización",
            "no_author_metrics": "No se han encontrado métricas para el autor seleccionado.",
            "author_network_for": "Red de colaboración para",
            "filtered_publications_list": "Listado de publicaciones filtradas",
            "showing_count": "Mostrando {count} publicaciones que cumplen los filtros seleccionados.",
            "no_publications": "No hay publicaciones que cumplan los filtros seleccionados.",
            "title": "Título",
            "year": "Año",
            "footer": "Este informe ha sido generado automáticamente por la plataforma de Bibliometría IPBLN.",
        },
        "en": {
            "meta_title": "IPBLN Bibliometrics: Report",
            "report_title_author": "Bibliometric report for {author}",
            "report_title_filters": "IPBLN Bibliometrics: Report generated with custom filters",
            "generated_on": "Generated on",
            "all_areas": "All areas",
            "all_institutions": "All institutions",
            "all_types": "All publication types",
            "all_quartiles": "All quartiles",
            "all_citations": "All (0 - max)",
            "max": "max",
            "year_from": "Year from",
            "year_to": "Year to",
            "thematic_areas": "Thematic areas",
            "institutions": "Institutions",
            "publication_types": "Publication types",
            "quartiles": "Quartiles",
            "citations_range": "Citations (min - max)",
            "selected_author": "Selected author",
            "timeline": "Publication timeline",
            "areas_bar": "Areas distribution (bar chart)",
            "areas_pie": "Areas distribution (pie chart)",
            "charts_missing": "Charts could not be exported.",
            "view_networks": "View collaboration networks",
            "departments": "Departments",
            "louvain": "Louvain",
            "leiden": "Leiden",
            "communities": "communities",
            "keywords_network": "Co-authorship network by keywords",
            "selected_author_metrics": "Selected author metrics",
            "orcid": "ORCID",
            "total_publications": "Total publications",
            "total_citations": "Total citations",
            "citations_wos": "WoS citations",
            "citations_scopus": "Scopus citations",
            "h_index": "h-index (WoS/Scopus)",
            "h_index_gb": "GESBIB h-index",
            "h_index_h5gb": "GESBIB h5-index",
            "international_index": "Internationalization index",
            "no_author_metrics": "No metrics found for the selected author.",
            "author_network_for": "Collaboration network for",
            "filtered_publications_list": "Filtered publications list",
            "showing_count": "Showing {count} publications matching the selected filters.",
            "no_publications": "There are no publications matching the selected filters.",
            "title": "Title",
            "year": "Year",
            "footer": "This report was generated automatically by the IPBLN Bibliometrics platform.",
        },
    }

    def t(key: str) -> str:
        return TXT[lang].get(key) or TXT["es"].get(key) or key

    publications = list(pubs_queryset)
    timeline_img = images.get("timeline")
    pie_img = images.get("pie")
    bar_img = images.get("bar")
    author_name = filters.get("author")

    buffer = BytesIO()
    doc_title = str(t("meta_title"))
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    doc.title = doc_title
    elements = []
    styles = getSampleStyleSheet()

    title = (
        t("report_title_author").format(author=author_name)
        if author_name
        else t("report_title_filters")
    )
    if lang == "en":
        fecha = datetime.now().strftime("%Y-%m-%d %H:%M")
    else:
        fecha = datetime.now().strftime("%d/%m/%Y %H:%M")
    subtitle = f"{t('generated_on')}: {fecha}"

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    subtitle_style = styles["Heading3"]
    subtitle_style.alignment = TA_CENTER
    elements.append(Paragraph(title, title_style))
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(Paragraph(subtitle, subtitle_style))
    elements.append(Spacer(1, 0.7 * cm))

    default_year_from = "1965"
    default_year_to = "2025"
    default_areas = t('all_areas')
    default_institutions = t('all_institutions')
    default_types = t('all_types')
    default_quartiles = t('all_quartiles')
    default_citations = t('all_citations')

    normal = styles["Normal"]

    def safe_value(value, default):
        if isinstance(value, (list, tuple)):
            return Paragraph(", ".join(value) if value else default, normal)
        return Paragraph(str(value) if value else default, normal)

    def label(text):
        return Paragraph(f"<b>{text}</b>", normal)

    citations_from = filters.get("citations_from") or "0"
    citations_to = filters.get("citations_to") or t('max')

    filters_data = [
        [label(t('year_from')), safe_value(filters.get('year_from'), default_year_from)],
        [label(t('year_to')), safe_value(filters.get('year_to'), default_year_to)],
        [label(t('thematic_areas')), safe_value(filters.get('areas'), default_areas)],
        [label(t('institutions')), safe_value(filters.get('institutions'), default_institutions)],
        [label(t('publication_types')), safe_value(filters.get('types'), default_types)],
        [label(t('quartiles')), safe_value(filters.get('quartiles'), default_quartiles)],
        [
            label(t('citations_range')),
            safe_value(
                f"{citations_from} - {citations_to}" if (filters.get('citations_from') or filters.get('citations_to')) else None,
                default_citations,
            ),
        ],
    ]
    if author_name:
        filters_data.append([label(t('selected_author')), safe_value(author_name, '-')])

    table = Table(filters_data, colWidths=[5 * cm, 10 * cm])
    table.setStyle(
        TableStyle(
            [
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 11),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LINEBELOW', (0, 0), (-1, -1), 0.25, colors.grey),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 1 * cm))

    media_url = settings.MEDIA_URL.rstrip('/') or '/media'
    base_url = request.build_absolute_uri(f"{media_url}/networks_html/")
    link_style = ParagraphStyle(
        'LinkStyle',
        parent=styles['Normal'],
        textColor=blue,
        underline=True,
        fontSize=12,
    )

    def add_image_section(title_text: str, image_b64: Optional[str]) -> None:
        if not image_b64:
            return
        elements.append(Paragraph(f'<b>{title_text}</b>', styles['Heading4']))
        elements.append(Spacer(1, 0.2 * cm))
        payload = image_b64.split(',')[1] if image_b64.startswith('data:image') else image_b64
        try:
            img_bytes = base64.b64decode(payload)
        except ValueError:
            logger.warning('Invalid base64 payload received for PDF export image.')
            return
        img_io = BytesIO(img_bytes)
        elements.append(Image(img_io, width=18 * cm, height=9 * cm))
        elements.append(Spacer(1, 0.7 * cm))

    elements.append(PageBreak())
    if timeline_img:
        add_image_section(t('timeline'), timeline_img)
    else:
        logger.warning('Timeline image missing for PDF export.')

    if bar_img:
        add_image_section(t('areas_bar'), bar_img)
    elif pie_img:
        add_image_section(t('areas_pie'), pie_img)
    else:
        logger.warning('Area distribution images missing for PDF export.')
        elements.append(Paragraph(f"<b>{t('charts_missing')}</b>", styles['Heading4']))
        elements.append(Spacer(1, 0.7 * cm))

    elements.append(Spacer(1, 0.7 * cm))
    section_title = t('view_networks')
    departments_label = t('departments')
    louvain_label = t('louvain')
    leiden_label = t('leiden')
    communities_label = t('communities')
    elements.append(Paragraph(f"<b>{section_title}:</b>", styles["Heading4"]))
    elements.append(
        Paragraph(
            f'<a href="{base_url}departments_comunidades.html">{departments_label}</a>',
            link_style,
        )
    )
    elements.append(
        Paragraph(
            f'<a href="{base_url}lovaina_comunidades.html">{louvain_label} (7 {communities_label})</a>',
            link_style,
        )
    )
    elements.append(
        Paragraph(
            f'<a href="{base_url}leiden_comunidades.html">{leiden_label} (6 {communities_label})</a>',
            link_style,
        )
    )
    if network_html:
        keywords_label = t('keywords_network')
        elements.append(
            Paragraph(
                f'<a href="{base_url}{network_html}">{keywords_label}</a>',
                link_style,
            )
        )

    if author_name:
        elements.append(Spacer(1, 0.5 * cm))
        elements.append(Paragraph(f"<b>{t('selected_author_metrics')}</b>", styles['Heading3']))
        try:
            author_obj = Author.objects.get(name=author_name)
            metrics = [
                (t('orcid'), author_obj.orcid_link or '-'),
                (t('total_publications'), author_obj.total_publications or '-'),
                (t('total_citations'), author_obj.total_citations or '-'),
                (t('citations_wos'), author_obj.citations_wos or '-'),
                (t('citations_scopus'), author_obj.citations_scopus or '-'),
                (t('h_index'), author_obj.h_index or '-'),
                (t('h_index_gb'), author_obj.h_index_gb or '-'),
                (t('h_index_h5gb'), author_obj.h_index_h5gb or '-'),
                (t('international_index'), author_obj.international_index or '-'),
            ]
            author_table = Table(metrics, colWidths=[7 * cm, 8 * cm])
            author_table.setStyle(
                TableStyle(
                    [
                        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                        ('FONTSIZE', (0, 0), (-1, -1), 11),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                        ('TOPPADDING', (0, 0), (-1, -1), 8),
                        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                        ('LINEBELOW', (0, 0), (-1, -1), 0.25, colors.grey),
                    ]
                )
            )
            elements.append(author_table)
        except Author.DoesNotExist:
            elements.append(Paragraph(f"<b>{t('no_author_metrics')}</b>", styles['Normal']))
        elements.append(Spacer(1, 0.7 * cm))

        def slugify(value: str) -> str:
            normalized = unicodedata.normalize('NFKD', value).encode('ascii', 'ignore').decode('ascii')
            return (
                normalized.replace(' ', '_')
                .replace('/', '_')
                .replace(',', '')
                .replace('.', '')
            )

        author_slug = slugify(author_name)
        author_html = f'collab_{author_slug}.html'
        author_network_label = t('author_network_for')
        elements.append(
            Paragraph(
                f'<a href="{base_url}{author_html}">{author_network_label} {author_name}</a>',
                link_style,
            )
        )
        elements.append(Spacer(1, 1 * cm))

    elements.append(PageBreak())
    elements.append(Paragraph(f"<b>{t('filtered_publications_list')}</b>", styles['Heading2']))
    num_pubs = len(publications)
    elements.append(
        Paragraph(
            t('showing_count').format(count=num_pubs),
            styles['Normal'],
        )
    )
    elements.append(Spacer(1, 0.2 * cm))

    if not publications:
        elements.append(Paragraph(t('no_publications'), styles['Normal']))
    else:
        script_prefix = (settings.FORCE_SCRIPT_NAME or '').rstrip('/')
        headings = [
            Paragraph(f"<b>{t('title')}</b>", styles['Normal']),
            Paragraph(f"<b>{t('year')}</b>", styles['Normal']),
        ]
        table_rows = [headings]
        for pub in publications:
            if script_prefix:
                pub_path = f"{script_prefix}/publication/{pub.id}"
            else:
                pub_path = f"/publication/{pub.id}"
            pub_url = request.build_absolute_uri(pub_path)
            title_link = f'<a href="{pub_url}">{pub.title}</a>'
            table_rows.append([Paragraph(title_link, link_style), str(pub.year) if pub.year else '-'])

        pubs_table = Table(table_rows, colWidths=[13 * cm, 2.5 * cm])
        pubs_table.setStyle(
            TableStyle(
                [
                    ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                    ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                    ('TOPPADDING', (0, 0), (-1, -1), 6),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('LINEBELOW', (0, 0), (-1, -1), 0.25, colors.grey),
                ]
            )
        )
        elements.append(pubs_table)

    def add_footer(canvas_obj, doc_obj):
        footer_text = t('footer')
        canvas_obj.saveState()
        canvas_obj.setFont('Helvetica', 9)
        canvas_obj.setFillColor(colors.grey)
        width, height = A4
        canvas_obj.drawCentredString(width / 2, 1.2 * cm, footer_text)
        canvas_obj.restoreState()

    def set_metadata(canvas_obj, doc_obj):
        canvas_obj.setTitle(doc_title)
        add_footer(canvas_obj, doc_obj)

    doc.build(elements, onFirstPage=set_metadata, onLaterPages=add_footer)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
