"""PDF export helpers for bibliometrics reports."""

from __future__ import annotations

import base64
import logging
import unicodedata
from datetime import datetime
from io import BytesIO
from typing import Iterable, Mapping, Optional

from django.conf import settings
from django.http import HttpRequest
from django.utils.translation import gettext as _
from reportlab.lib import colors
from reportlab.lib.colors import blue
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from bibliodata.models import Author, Publication


def build_pdf_report(
    *,
    request: HttpRequest,
    pubs_queryset: Iterable[Publication],
    filters: Mapping[str, object],
    images: Mapping[str, Optional[str]],
    network_html: Optional[str],
    logger: Optional[logging.Logger] = None,
) -> bytes:
    """Build the bibliometrics PDF report and return the generated bytes."""

    logger = logger or logging.getLogger("django")
    publications = list(pubs_queryset)
    timeline_img = images.get("timeline")
    pie_img = images.get("pie")
    bar_img = images.get("bar")
    author_name = filters.get("author")

    buffer = BytesIO()
    doc_title = "Bibliometría IPBLN: Informe"
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    doc.title = doc_title
    elements = []
    styles = getSampleStyleSheet()

    title = (
        f"{_('Informe bibliométrico de')} {author_name}"
        if author_name
        else _('Bibliometría IPBLN: Informe generado con filtros personalizados')
    )
    fecha = datetime.now().strftime("%d/%m/%Y %H:%M")
    subtitle = f"{_('Fecha de generación')}: {fecha}"

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    subtitle_style = styles["Heading3"]
    subtitle_style.alignment = TA_CENTER
    elements.append(Paragraph(title, title_style))
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(Paragraph(subtitle, subtitle_style))
    elements.append(Spacer(1, 0.7 * cm))

    default_year_from = "1965"
    default_year_to = "2025"
    default_areas = _('Todas las áreas')
    default_institutions = _('Todas las instituciones')
    default_types = _('Todos los tipos')
    default_quartiles = _('Todos los cuartiles')
    default_citations = _('Todas (0 - máx)')

    normal = styles["Normal"]

    def safe_value(value, default):
        if isinstance(value, (list, tuple)):
            return Paragraph(", ".join(value) if value else default, normal)
        return Paragraph(str(value) if value else default, normal)

    def label(text):
        return Paragraph(f"<b>{text}</b>", normal)

    citations_from = filters.get("citations_from") or "0"
    citations_to = filters.get("citations_to") or _('máx')

    filters_data = [
        [label(_('Año desde')), safe_value(filters.get('year_from'), default_year_from)],
        [label(_('Año hasta')), safe_value(filters.get('year_to'), default_year_to)],
        [label(_('Áreas temáticas')), safe_value(filters.get('areas'), default_areas)],
        [label(_('Instituciones')), safe_value(filters.get('institutions'), default_institutions)],
        [label(_('Tipos de publicación')), safe_value(filters.get('types'), default_types)],
        [label(_('Cuartiles')), safe_value(filters.get('quartiles'), default_quartiles)],
        [
            label(_('Citas (mín - máx)')),
            safe_value(
                f"{citations_from} - {citations_to}" if (filters.get('citations_from') or filters.get('citations_to')) else None,
                default_citations,
            ),
        ],
    ]
    if author_name:
        filters_data.append([label(_('Autor seleccionado')), safe_value(author_name, '-')])

    table = Table(filters_data, colWidths=[5 * cm, 10 * cm])
    table.setStyle(
        TableStyle(
            [
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 11),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LINEBELOW', (0, 0), (-1, -1), 0.25, colors.grey),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 1 * cm))

    media_url = settings.MEDIA_URL.rstrip('/') or '/media'
    base_url = request.build_absolute_uri(f"{media_url}/networks_html/")
    link_style = ParagraphStyle(
        'LinkStyle',
        parent=styles['Normal'],
        textColor=blue,
        underline=True,
        fontSize=12,
    )

    def add_image_section(title_text: str, image_b64: Optional[str]) -> None:
        if not image_b64:
            return
        elements.append(Paragraph(f'<b>{title_text}</b>', styles['Heading4']))
        elements.append(Spacer(1, 0.2 * cm))
        payload = image_b64.split(',')[1] if image_b64.startswith('data:image') else image_b64
        try:
            img_bytes = base64.b64decode(payload)
        except ValueError:
            logger.warning('Invalid base64 payload received for PDF export image.')
            return
        img_io = BytesIO(img_bytes)
        elements.append(Image(img_io, width=18 * cm, height=9 * cm))
        elements.append(Spacer(1, 0.7 * cm))

    elements.append(PageBreak())
    if timeline_img:
        add_image_section(_('Línea temporal de publicaciones'), timeline_img)
    else:
        logger.warning('Timeline image missing for PDF export.')

    if bar_img:
        add_image_section(_('Distribución de áreas (gráfico de barras)'), bar_img)
    elif pie_img:
        add_image_section(_('Distribución de áreas (gráfico circular)'), pie_img)
    else:
        logger.warning('Area distribution images missing for PDF export.')
        elements.append(Paragraph('<b>No se han podido exportar los gráficos.</b>', styles['Heading4']))
        elements.append(Spacer(1, 0.7 * cm))

    elements.append(Spacer(1, 0.7 * cm))
    elements.append(Paragraph('<b>Visualizar redes de colaboración entre IPs:</b>', styles['Heading4']))
    elements.append(Paragraph(f'<a href="{base_url}departments_comunidades.html">Departamentos</a>', link_style))
    elements.append(Paragraph(f'<a href="{base_url}lovaina_comunidades.html">Lovaina (7 comunidades)</a>', link_style))
    elements.append(Paragraph(f'<a href="{base_url}leiden_comunidades.html"> Leiden (6 comunidades)</a>', link_style))
    if network_html:
        elements.append(Paragraph(f'<a href="{base_url}{network_html}">Red de Coautorías por Palabras Clave</a>', link_style))

    if author_name:
        elements.append(Spacer(1, 0.5 * cm))
        elements.append(Paragraph('<b>Métricas del autor seleccionado</b>', styles['Heading3']))
        try:
            author_obj = Author.objects.get(name=author_name)
            metrics = [
                (_('ORCID'), author_obj.orcid_link or '-'),
                (_('Total publicaciones'), author_obj.total_publications or '-'),
                (_('Total citas'), author_obj.total_citations or '-'),
                (_('Citas WoS'), author_obj.citations_wos or '-'),
                (_('Citas Scopus'), author_obj.citations_scopus or '-'),
                (_('Índice h (WoS/Scopus)'), author_obj.h_index or '-'),
                (_('Índice h GESBIB'), author_obj.h_index_gb or '-'),
                (_('Índice h5 GESBIB'), author_obj.h_index_h5gb or '-'),
                (_('Índice internacionalización'), author_obj.international_index or '-'),
            ]
            author_table = Table(metrics, colWidths=[7 * cm, 8 * cm])
            author_table.setStyle(
                TableStyle(
                    [
                        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                        ('FONTSIZE', (0, 0), (-1, -1), 11),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                        ('TOPPADDING', (0, 0), (-1, -1), 8),
                        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                        ('LINEBELOW', (0, 0), (-1, -1), 0.25, colors.grey),
                    ]
                )
            )
            elements.append(author_table)
        except Author.DoesNotExist:
            elements.append(Paragraph('<b>No se han encontrado métricas para el autor seleccionado.</b>', styles['Normal']))
        elements.append(Spacer(1, 0.7 * cm))

        def slugify(value: str) -> str:
            normalized = unicodedata.normalize('NFKD', value).encode('ascii', 'ignore').decode('ascii')
            return (
                normalized.replace(' ', '_')
                .replace('/', '_')
                .replace(',', '')
                .replace('.', '')
            )

        author_slug = slugify(author_name)
        author_html = f'collab_{author_slug}.html'
        elements.append(Paragraph(f'<a href="{base_url}{author_html}">Red de colaboración de {author_name}</a>', link_style))
        elements.append(Spacer(1, 1 * cm))

    elements.append(PageBreak())
    elements.append(Paragraph('<b>Listado de publicaciones filtradas</b>', styles['Heading2']))
    num_pubs = len(publications)
    elements.append(Paragraph(f'Se muestran {num_pubs} publicaciones que cumplen los filtros seleccionados.', styles['Normal']))
    elements.append(Spacer(1, 0.2 * cm))

    if not publications:
        elements.append(Paragraph('No hay publicaciones que coincidan con los filtros seleccionados.', styles['Normal']))
    else:
        script_prefix = (settings.FORCE_SCRIPT_NAME or '').rstrip('/')
        headings = [Paragraph('<b>Título</b>', styles['Normal']), Paragraph('<b>Año</b>', styles['Normal'])]
        table_rows = [headings]
        for pub in publications:
            if script_prefix:
                pub_path = f"{script_prefix}/publication/{pub.id}"
            else:
                pub_path = f"/publication/{pub.id}"
            pub_url = request.build_absolute_uri(pub_path)
            title_link = f'<a href="{pub_url}">{pub.title}</a>'
            table_rows.append([Paragraph(title_link, link_style), str(pub.year) if pub.year else '-'])

        pubs_table = Table(table_rows, colWidths=[13 * cm, 2.5 * cm])
        pubs_table.setStyle(
            TableStyle(
                [
                    ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                    ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                    ('TOPPADDING', (0, 0), (-1, -1), 6),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('LINEBELOW', (0, 0), (-1, -1), 0.25, colors.grey),
                ]
            )
        )
        elements.append(pubs_table)

    def add_footer(canvas_obj, doc_obj):
        footer_text = _('Este informe ha sido generado automáticamente por la plataforma de Bibliometría IPBLN.')
        canvas_obj.saveState()
        canvas_obj.setFont('Helvetica', 9)
        canvas_obj.setFillColor(colors.grey)
        width, height = A4
        canvas_obj.drawCentredString(width / 2, 1.2 * cm, footer_text)
        canvas_obj.restoreState()

    def set_metadata(canvas_obj, doc_obj):
        canvas_obj.setTitle(doc_title)
        add_footer(canvas_obj, doc_obj)

    doc.build(elements, onFirstPage=set_metadata, onLaterPages=add_footer)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
