# Generated by Django 5.2 on 2025-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='researcher_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='All Researcher IDs (WoS)'),
        ),
        migrations.AddField(
            model_name='author',
            name='scopus_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='All Scopus IDs'),
        ),
    ]
