# Generated by Django 5.2 on 2025-05-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0002_author_researcher_ids_author_scopus_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationDuplication',
        ),
    ]
