# Generated by Django 5.2 on 2025-05-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0003_delete_publicationduplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='conciencia_id',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='digital_csic_id',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='indices_id',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_csic',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='open_access',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='scopus_id',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='wos_id',
        ),
        migrations.AddField(
            model_name='publication',
            name='aa_link',
            field=models.URLField(blank=True, null=True, verbose_name='External PDF link (AA)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='publication',
            name='affiliations',
            field=models.JSONField(blank=True, null=True, verbose_name='Affiliations'),
        ),
        migrations.AddField(
            model_name='publication',
            name='areas_all',
            field=models.JSONField(blank=True, null=True, verbose_name='All thematic areas'),
        ),
        migrations.AddField(
            model_name='publication',
            name='citations',
            field=models.IntegerField(blank=True, null=True, verbose_name='Citations'),
        ),
        migrations.AddField(
            model_name='publication',
            name='conference_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Conference date'),
        ),
        migrations.AddField(
            model_name='publication',
            name='conference_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Conference location'),
        ),
        migrations.AddField(
            model_name='publication',
            name='conference_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Conference name'),
        ),
        migrations.AddField(
            model_name='publication',
            name='editorial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='publication',
            name='editorial_link',
            field=models.URLField(blank=True, null=True, verbose_name='Editorial link'),
        ),
        migrations.AddField(
            model_name='publication',
            name='extra_links',
            field=models.JSONField(blank=True, null=True, verbose_name='Extra source links'),
        ),
        migrations.AddField(
            model_name='publication',
            name='extra_sources',
            field=models.JSONField(blank=True, null=True, verbose_name='Sources (WOS, SCOPUS...)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='international_collab',
            field=models.BooleanField(default=False, verbose_name='International collaboration'),
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ISBN (for books)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='issns',
            field=models.JSONField(blank=True, null=True, verbose_name='ISSNs'),
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords_all',
            field=models.JSONField(blank=True, null=True, verbose_name='All keywords'),
        ),
        migrations.AddField(
            model_name='publication',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='publication',
            name='num_countries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of countries'),
        ),
        migrations.AddField(
            model_name='publication',
            name='num_foreign_affils',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of foreign affiliations'),
        ),
        migrations.AddField(
            model_name='publication',
            name='num_spanish_affils',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Spanish affiliations'),
        ),
        migrations.AddField(
            model_name='publication',
            name='provinces',
            field=models.JSONField(blank=True, null=True, verbose_name='Provinces'),
        ),
        migrations.AddField(
            model_name='publication',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source ID'),
        ),
        migrations.AddField(
            model_name='publication',
            name='source_link',
            field=models.URLField(blank=True, null=True, verbose_name='Source link'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to title'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Publication date (yyyy-mm-dd)'),
        ),
    ]
