# Generated by Django 5.2 on 2025-05-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0004_remove_publication_conciencia_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicationmetric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='publicationmetric',
            name='international_collab',
            field=models.BooleanField(blank=True, null=True, verbose_name='International collaboration (metric)'),
        ),
        migrations.AddField(
            model_name='publicationmetric',
            name='metric_type',
            field=models.CharField(choices=[('jif', 'Journal Impact Factor'), ('jci', 'Journal Citation Indicator'), ('sjr', 'SJR'), ('citescore', 'CiteScore'), ('influence', 'Article Influence Score'), ('citations', 'Citations'), ('recent_citations', 'Recent Citations (2y)'), ('fcr', 'Field Citation Ratio'), ('rcr', 'Relative Citation Ratio')], default='Not specified', max_length=50, verbose_name='Metric type'),
        ),
        migrations.AddField(
            model_name='publicationmetric',
            name='source_journal_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to journal'),
        ),
        migrations.AddField(
            model_name='publicationmetric',
            name='source_journal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Journal name for metric'),
        ),
        migrations.AddField(
            model_name='publicationmetric',
            name='subject_areas',
            field=models.JSONField(blank=True, null=True, verbose_name='Subject areas'),
        ),
        migrations.AlterField(
            model_name='publicationmetric',
            name='impact_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Impact factor / value'),
        ),
        migrations.AlterField(
            model_name='publicationmetric',
            name='influence_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Influence score (if applicable)'),
        ),
        migrations.AlterField(
            model_name='publicationmetric',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='publicationmetric',
            name='source',
            field=models.CharField(choices=[('wos', 'WoS'), ('scopus', 'Scopus'), ('dimensions', 'Dimensions')], max_length=50, verbose_name='Metric source'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationmetric',
            unique_together={('publication', 'source', 'metric_type', 'year')},
        ),
    ]
