# Generated by Django 5.2 on 2025-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0005_alter_publicationmetric_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='other_authors',
            field=models.JSONField(blank=True, null=True, verbose_name='Non-IPBLN authors (raw names)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='other_institutions',
            field=models.JSONField(blank=True, null=True, verbose_name='Other institutions (non-CSIC)'),
        ),
    ]
