# Generated by Django 5.2 on 2025-05-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0008_remove_publication_other_institutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='conference_date',
            field=models.JSONField(blank=True, null=True, verbose_name='Conference date(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='conference_location',
            field=models.JSONField(blank=True, null=True, verbose_name='Conference location(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='conference_name',
            field=models.JSONField(blank=True, null=True, verbose_name='Conference name(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.JSONField(blank=True, null=True, verbose_name='DOI(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.JSONField(blank=True, null=True, verbose_name='ISBNs (for books)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.JSONField(max_length=100, verbose_name='Normalized type(s)'),
        ),
    ]
