# Generated by Django 5.2 on 2025-05-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0009_alter_publication_conference_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.JSONField(blank=True, null=True, verbose_name='Normalized type(s)'),
        ),
    ]
