# Generated by Django 5.2 on 2025-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0010_alter_publication_publication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationmetric',
            name='international_collab',
            field=models.FloatField(blank=True, null=True, verbose_name='International collaboration (metric)'),
        ),
    ]
