# Generated by Django 5.2 on 2025-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0011_alter_publicationmetric_international_collab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='international_collab',
            field=models.FloatField(blank=True, null=True, verbose_name='International collaboration'),
        ),
    ]
