# Generated by Django 5.2 on 2025-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0013_publication_jcr_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Department'),
        ),
    ]
