# Generated by Django 5.2 on 2025-06-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0014_author_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='leiden_community',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leiden Community'),
        ),
        migrations.AddField(
            model_name='author',
            name='lovaina_community',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lovaina Community'),
        ),
    ]
