# Generated by Django 5.2 on 2025-06-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0015_author_leiden_community_author_lovaina_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_count', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_initiated', to='bibliodata.author')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_received', to='bibliodata.author')),
            ],
            options={
                'unique_together': {('author', 'collaborator')},
            },
        ),
    ]
