# Generated by Django 5.2 on 2025-06-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0016_collaboration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
