# Generated by Django 5.2 on 2025-06-09 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0017_delete_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorClustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('kmeans', 'KMeans'), ('dbscan', 'DBSCAN'), ('hdbscan', 'HDBSCAN'), ('agglomerative', 'Agglomerative'), ('hierarchical', 'Hierarchical'), ('spectral', 'Spectral'), ('gmm', 'Gaussian Mixture Model')], max_length=50, verbose_name='Clustering model')),
                ('cluster', models.IntegerField(verbose_name='Assigned cluster')),
                ('k', models.IntegerField(blank=True, null=True, verbose_name='Number of clusters')),
                ('pca_dims', models.IntegerField(blank=True, null=True, verbose_name='PCA dimensions')),
                ('silhouette', models.FloatField(blank=True, null=True, verbose_name='Silhouette score')),
                ('calinski_harabasz', models.FloatField(blank=True, null=True, verbose_name='Calinski-Harabasz score')),
                ('davies_bouldin', models.FloatField(blank=True, null=True, verbose_name='Davies-Bouldin score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusterings', to='bibliodata.author')),
            ],
            options={
                'verbose_name': 'Author clustering',
                'verbose_name_plural': 'Author clusterings',
                'indexes': [models.Index(fields=['model_name', 'k', 'pca_dims'], name='bibliodata__model_n_fd1d58_idx')],
            },
        ),
    ]
