# Generated by Django 5.2 on 2025-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0018_authorclustering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclustering',
            name='model_name',
            field=models.CharField(choices=[('kmeans', 'KMeans'), ('dbscan', 'DBSCAN'), ('hdbscan', 'HDBSCAN'), ('agglomerative', 'Agglomerative'), ('hierarchical', 'Hierarchical'), ('spectral', 'Spectral'), ('gmm', 'Gaussian Mixture Model'), ('lovaina', 'Lovaina')], max_length=50, verbose_name='Clustering model'),
        ),
    ]
