# Generated by Django 5.2 on 2025-06-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0019_alter_authorclustering_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='department_global',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Department for global network'),
        ),
        migrations.AddField(
            model_name='author',
            name='leiden_community_global',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leiden Community for global network'),
        ),
        migrations.AddField(
            model_name='author',
            name='lovaina_community_global',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lovaina Community for global network'),
        ),
    ]
