# Generated by Django 5.2 on 2025-06-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0020_author_department_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='predicted_thematic_areas',
            field=models.ManyToManyField(blank=True, related_name='predicted_publications', to='bibliodata.thematicarea'),
        ),
    ]
