# Generated by Django 5.2 on 2025-07-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0021_publication_predicted_thematic_areas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.DeleteModel(
            name='ThematicCluster',
        ),
    ]
