# Generated by Django 5.2 on 2025-09-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0022_delete_reporttemplate_delete_thematiccluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.TextField(verbose_name='Embedding vector (JSON or string)')),
                ('source_fields', models.JSONField(blank=True, null=True, verbose_name='Fields used for embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='bibliodata.publication')),
            ],
        ),
    ]
