# Generated by Django 5.2 on 2025-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0023_publicationembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='countries',
            field=models.JSONField(blank=True, null=True, verbose_name='Countries (names)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='countries_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='Countries IDs (from API)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='countries_iso2',
            field=models.JSONField(blank=True, null=True, verbose_name='Countries ISO A2'),
        ),
    ]
