# Generated by Django 5.2 on 2025-09-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliodata', '0024_publication_countries_publication_countries_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='normalized_types',
            field=models.JSONField(blank=True, null=True, verbose_name='Normalized type(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.JSONField(blank=True, null=True, verbose_name='Publication type(s)'),
        ),
    ]
